### ISSUE TITLE
Import fails with IAE "Email must not be null"

### ISSUE THREAD

**Issue by pilhuhn** [fabric8io/fabric8-generator#31]
Tried to create a project, this failed in step 4 with

----
ExecuteForgeCommandError
The forge-quick-start :: execute :: 4 command failed or only partially succeeded
message
Failed to import project to https://github.com/pilhuhn/osio-test-1.git. java.lang.IllegalArgumentException: E-mail address of PersonIdent must not be null.
status
FAILED
----

The repository itself was already created on GitHub at this time, so that a retry after pressing the OK button immediately fails as well.

A retry after deleting the created repo on GH fails with the same above message.

**Comment by pilhuhn** [comment]
Logfile from the Forge pod:

[forge-2.log.zip](https://github.com/fabric8io/fabric8-generator/files/1164907/forge-2.log.zip)

And my user inside f8 has an email set

![bildschirmfoto 2017-07-21 um 10 25 47](https://user-images.githubusercontent.com/208246/28455349-0f37365a-6dff-11e7-990e-315b25c069d8.png)

**Comment by corinnekrych** [comment]
The issue is when your github settings hide your email address AND block github push showing address.

To get passed the error with null address, default it to an "invalid" email. See associated PR https://github.com/fabric8io/fabric8-generator/pull/50.

However if you have `block command line pushes that expose my email` checked, you will create an empty repo (nothing pushed). The wizard failed silently (no exception thrown).
![screenshot 2017-08-23 13 42 50](https://user-images.githubusercontent.com/1395710/29616015-35fc412e-8810-11e7-9629-fc4176f2069f.png)

This is an issue in fabric8 https://github.com/fabric8io/fabric8/issues/6919 
when a push is done, this line https://github.com/fabric8io/fabric8/blob/master/components/fabric8-project-utils/src/main/java/io/fabric8/project/support/GitUtils.java#L199 return a warning/error code in result.getMessages() == `error: GH007: Your push would publish a private email address.
You can make your email public or disable this protection by visiting:
http://github.com/settings/emails`, we should take this output and thrown it in an exception (instead of silently swallow it)

**Comment by pilhuhn** [comment]
@corinnekrych I don't have "Keep my email address private" enabled and thus the "Block ..." option is not even visible.

**Comment by corinnekrych** [comment]
@pilhuhn weird when I look at your profile i don't see any email. Could you try the fix once pushed to prod?
